# 4. Numpy 기본: 배열과 벡터 연산

In [1]:
import numpy as np

my_arr = np.arange(1000000)

my_list = list(range(1000000))

In [2]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 22.9 ms


In [3]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 849 ms


## 4.1 Numpy ndarray: 다차원 배열 객체
-----

In [4]:
import numpy as np

# 임의의 값을 생성
data = np.random.randn(2,3)

In [5]:
data

array([[-0.4535449 , -0.00806671, -2.52286424],
       [ 0.19781117, -1.29192469,  1.38320153]])

In [6]:
data * 10

array([[ -4.53544899,  -0.08066714, -25.22864238],
       [  1.97811173, -12.91924688,  13.83201528]])

In [7]:
data + data

array([[-0.9070898 , -0.01613343, -5.04572848],
       [ 0.39562235, -2.58384938,  2.76640306]])

In [9]:
data.shape

(2, 3)

In [10]:
data.dtype

dtype('float64')

###  4.1.1 ndarray 생성하기
----- 

In [11]:
data1 = [6, 7.5, 8, 0, 1]

In [12]:
arr1 = np.array(data1)

In [13]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [14]:
data2 = [[1,2,3,4], [5,6,7,8]]

In [15]:
arr2 = np.array(data2)

In [16]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
arr2.ndim

2

In [18]:
arr2.shape

(2, 4)

In [19]:
arr1.dtype

dtype('float64')

In [20]:
arr2.dtype

dtype('int32')

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [25]:
np.zeros((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [26]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
arr3 = np.asarray(arr1)

In [28]:
arr3

array([6. , 7.5, 8. , 0. , 1. ])

In [33]:
aranged = np.arange(9)
aranged

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [31]:
type(aranged)

numpy.ndarray

In [61]:
np.ones(1)

array([1.])

In [62]:
np.ones([1])

array([1.])

In [63]:
np.ones((1))

array([1.])

In [39]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [40]:
np.ones((3,3), int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [41]:
np.ones((3,3), float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [42]:
np.ones((3,3), str)

array([['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1']], dtype='<U1')

In [43]:
np.ones((3,3), bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [55]:
np.ones_like([[0,0,0], [0,0,0]])

array([[1, 1, 1],
       [1, 1, 1]])

In [60]:
np.ones_like(1)

array(1)

In [59]:
np.ones_like([1])

array([1])

In [56]:
np.ones_like(((0,0,0), (0,0,0)))

array([[1, 1, 1],
       [1, 1, 1]])

In [57]:
np.ones_like({{0,0,0}, {0,0,0}})

TypeError: unhashable type: 'set'

In [64]:
np.zeros(1)

array([0.])

In [70]:
np.zeros(3)

array([0., 0., 0.])

In [65]:
np.zeros([1])

array([0.])

In [71]:
np.zeros([3])

array([0., 0., 0.])

In [66]:
np.zeros((1))

array([0.])

In [68]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [72]:
np.zeros([3,3,3])

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [74]:
np.empty(3)

array([0., 0., 0.])

In [75]:
np.empty([3])

array([0., 0., 0.])

In [76]:
np.empty([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [77]:
np.empty([3,3,3])

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [81]:
np.empty([1,1,1])

array([[[1.]]])

In [82]:
np.empty([2,2,2])

array([[[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 3.89323729e-321],
        [1.97345609e-312, 1.86922094e-306]]])

In [83]:
np.empty([3,3,3])

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [106]:
arr4 = np.full((1,2), np.inf)
arr4

array([[inf, inf]])

In [98]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [99]:
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

## 4.1.2 ndarray의 dtype
-----

In [108]:
arr1 = np.array([1,2,3], dtype=np.float64)
arr2 = np.array([1,2,3], dtype=np.int32)

In [109]:
arr1.dtype

dtype('float64')

NameError: name 'dtype' is not defined