In [2]:
import numpy as np

A = np.array([[1,1,0], [0,1,1], [1,1,1]])
A

array([[1, 1, 0],
       [0, 1, 1],
       [1, 1, 1]])

In [3]:
Ainv = np.linalg.inv(A)
Ainv

array([[ 0., -1.,  1.],
       [ 1.,  1., -1.],
       [-1.,  0.,  1.]])

In [4]:
b = np.array([[2], [2], [3]])
b

array([[2],
       [2],
       [3]])

In [5]:
x = Ainv @ b
x

array([[1.],
       [1.],
       [1.]])

In [6]:
A @ x - b

array([[0.],
       [0.],
       [0.]])

In [ ]:
lstsq() 