In [1]:
import numpy

In [6]:
array1 = numpy.array([2,3,5,7,11,13,17,19,23,29,31])

In [7]:
array1

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31])

In [8]:
type(array1)

numpy.ndarray

In [9]:
array.shape

(11,)

In [11]:
array2 = numpy.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [12]:
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
array2.shape

(3, 4)

In [15]:
array3 = numpy.array([[[1],[2],[3],[4]], [[5],[6],[7],[8]], [[9],[10],[11],[12]]])

In [16]:
array3

array([[[ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8]],

       [[ 9],
        [10],
        [11],
        [12]]])

In [17]:
array3.shape

(3, 4, 1)

In [18]:
array4 = numpy.full(6,7)

In [19]:
print(array4)

[7 7 7 7 7 7]


In [20]:
array5 = numpy.zeros(6, dtype=int)

In [21]:
array5

array([0, 0, 0, 0, 0, 0])

In [23]:
array6 = numpy.ones(6, dtype=int)

In [24]:
array6

array([1, 1, 1, 1, 1, 1])

In [25]:
array7 = numpy.random.random(6)

In [26]:
array7

array([0.53874868, 0.70827823, 0.40762774, 0.21493351, 0.39409964,
       0.59418831])

In [28]:
array8 = numpy.arange(6)

In [29]:
array8

array([0, 1, 2, 3, 4, 5])

In [39]:
array9 = numpy.arange(2,7)

In [40]:
print(array9)

[2 3 4 5 6]


In [41]:
array10 = numpy.arange(3, 17, 3)

In [42]:
array10

array([ 3,  6,  9, 12, 15])

In [44]:
import numpy as np

array1 = np.full(6,0)
array2 = np.zeros(6)
array3 = np.full(6,6)
array4 = np.random.random(6)
array5 = np.random.random(10)

In [45]:
array10[[1,3,4]]

array([ 6, 12, 15])

In [46]:
array11 = np.array([2,1,3])

In [47]:
array12 = array10[array11]

In [48]:
array12

array([ 9,  6, 12])

In [49]:
array10[2:5]

array([ 9, 12, 15])